version: '3.8'

services:
  meadow-paradise-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/build # Исключаем build папку
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
      - FAST_REFRESH=true
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
