name: Deploy to GitHub Pages

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for static export
        run: npm run build:static
        env:
          NODE_ENV: production

      - name: Remove large files from build
        run: |
          find ./build/client -name "*.jpg" -size +5M -delete || true
          find ./build/client -name "*.jpeg" -size +5M -delete || true
          find ./build/client -name "*.png" -size +5M -delete || true
          find ./build/client -name "*.webp" -size +5M -delete || true
          echo "Large files removed"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Check build size
        run: |
          du -sh ./build/client
          echo "Build directory size checked"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/client

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
