name: Deploy to GitHub Pages

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for static export
        run: npm run build:static
        env:
          NODE_ENV: production

      - name: Remove large files from build
        run: |
          find ./build/client -name "*.jpg" -size +5M -delete || true
          find ./build/client -name "*.jpeg" -size +5M -delete || true
          find ./build/client -name "*.png" -size +5M -delete || true
          find ./build/client -name "*.webp" -size +5M -delete || true
          echo "Large files removed"

      - name: Check build size
        run: |
          du -sh ./build/client
          echo "Build directory size checked"

      - name: List build contents
        run: |
          ls -la ./build/client/
          echo "Build contents listed"

      - name: Deploy to GitHub Pages
        run: |
          echo "Starting deployment to gh-pages branch..."
          cd ./build/client
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy from GitHub Actions - $(date)"
          echo "Pushing to gh-pages branch..."
          git push -f https://x-access-token:${{ secrets.GH_TOKEN  }}@github.com/Bruno-116aff/Meadow-Paradise.git HEAD:gh-pages
          echo "Deployment completed!"
        if: github.ref == 'refs/heads/master'
