name: Simple Deploy to GitHub Pages

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:static
        env:
          NODE_ENV: production

      - name: Remove large files
        run: |
          find ./build/client -name "*.jpg" -size +5M -delete || true
          find ./build/client -name "*.jpeg" -size +5M -delete || true
          find ./build/client -name "*.png" -size +5M -delete || true

      - name: Deploy
        run: |
          cd build/client
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy from GitHub Actions"
          git push -f https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Bruno-116aff/Meadow-Paradise.git HEAD:gh-pages
